# Generated by Django 2.1.7 on 2019-07-25 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='city',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
