# Generated by Django 2.1.7 on 2019-07-25 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0002_students_city'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='students',
            table='students',
        ),
    ]
